name: Process car park list
on:
  push:
    paths:
      - .github/workflows/flat.yml # Only run a new workflow every time this file (flat.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: # This workflow has 3 steps
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v3
      # This step installs Deno, which is a new Javascript runtime that improves on Node. We'll use it for postprocessing later
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      # Get 310
      - name: Fetch data
        uses: githubocto/flat@mr/node16
        with:
          http_url: ${{ secrets.MIPERMIT_URL }} # The data to fetch
          mask: true
          downloaded_filename: ./carparks/mi_permit_car_park_data_310.json # The http_url gets saved and renamed in our repository
          axios_config: ${{ secrets.MIPERMIT_310 }}
